sudo: false
language: node_js
matrix:
  include:
    - node_js: 10
    - node_js: 8
    - node_js: 6
  allow_failures:
    - node_js: 10
install:
  - npm install
  - npm install -g coveralls
script:
  - npm test
  - npm run coverage 
  - cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - development